version: "2"
services:
  # data-www
  data-www:
    container_name: ${NOME_PROJETO}_data-www
    image: busybox
    volumes:
      - /home/sena/Projetos/test_alfasoft/app:/app
    # mysql
  mysql:
    container_name: ${NOME_PROJETO}_mysql
    image: mysql:8.0.16
    volumes:
      - ./docker-assets/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT_HOST}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}      
  ## php-fpm
  php-fpm:
    container_name: ${NOME_PROJETO}_php-fpm
    build: ./docker-assets/php-fpm
    volumes_from:
      - data-www
    volumes:
      - ./docker-assets/php-fpm/scripts:/scripts
    links:
      - mysql      
    working_dir: ${DOCUMENT_ROOT}
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PHP_IDE_CONFIG: serverName=Local
      APP_NAME: ${NOME_PROJETO}docker-assets/php-fpm
    entrypoint: /scripts/setup.sh
    command: bash -c "tail -f /dev/null"
    
  # nginx
  nginx:
    container_name: ${NOME_PROJETO}_nginx
    build: ./docker-assets/nginx
    volumes_from:
      - data-www
    volumes:
      - ./docker-assets/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php-fpm
    ports:
      - "${NGINX_PORT}:8080"
      - "${NGINX_SECURE_PORT}:443"
    working_dir: ${DOCUMENT_ROOT}
